const data =[
    {
        id:1,
        category:"react js", 
        title:"Bombraid.com",
        stack:"#reactjs #scss #figma #probono",
        role:"developer",
        description:"The guide about how to prepare a cellar as a shelter in case of a bombraid - developed voluntarily as a quick response to the war in Ukraine. ",
        image:"/bombraid2.png",
        link:"/project/commercial/bombraid", 
        video: "/project_details/lsf.mp4",
        gif: "/project_details/Bombraid.gif",
       
    },
    {
        id:4,
        image:"/exlibris.png",
        title:"Exlibris",
        role:"", 
        stack:"#html #php #javascript #scss",
        link:"/project/commercial/exlibris", 
        description:"Web application with customised files generator for Musuem Łazienki Królewskie.",
        category:"applications",
       
    },
    {
        id:5,
        image:"/leica.png",
        title:"Leica Store Warsaw",
        role:"developer, e-commerce administrator", 
        stack:"#custom-wordpress #php #acf #jquery #scss",
        description:"E-coomerce store for Leica Store Warsaw. ",
        category:"e-commerce",
        link:"/project/commercial/leica-store-warsaw", 
       
    },
    {
        id:9,
        image:"/lsf.png",
        title:"Leica Street Photo",
        role:"developer, competition administrator", 
        stack:"#custom-wordpress #php #acf #jquery #scss",
        description:"A competition website for Leica Street Photo. ",
        category:"wordpress cms",
        link: "/project/commercial/leica-street-photo",
    },
    {
        id:2,
        image:"/dzialzagraniczny.png",
        title:"Dział zagraniczny",
        role:"developer, project manager", 
        description:"The platform for podcasts and articles about foreign affairs. ",
        category:"wordpress cms",
        link:"/project/commercial/dzial-zagraniczny", 
        stack:"#custom-wordpress",
        gif: "/project_details/dzial.gif",
    },
    {
        id:3,
        image:"/kissdentalcare.png",
        title:"Kiss Dental Care",
        role:"developer, project manager", 
        stack:"#custom-wordpress",
        description:"The website for innovative dental clinic.",
        category:"wordpress cms",
        link:"/project/commercial/kiss-dental-care", 
        gif: "/project_details/kiss.gif",
    },

 
    {
        id:6,
        image:"/uzdrowisko.png",
        title:"Uzdrowisko",
        role:"developer, project manager", 
        stack:"#reactjs #reactpress #wordpress #graphql #scss",
        description:"A simple portfolio for yoga teacher and chinese medicine practitioner.",
        category:"react js",
        link:"/project/commercial/uzdrowisko", 
       
    },
    {
        id:17,
        image:"/metamorfozy.png",
        title:"Metamorfozy",
        role:"developer, project manager", 
        stack:"#android-studio #java #interactive-kiosk",
        description:"Application made for Touchmonitor found in the White House of Łazienki Królewskie Park. ",
        category:"applications",
       
    },
    {
        id:7,
        image:"/wcs_short.png",
        title:"Warsaw Concept Store",
        role:"developer, project manager", 
        stack:"#custom-wordpress #php #acf #jquery #scss",
        description:"A store for Warsaw Concept Store - a shop with unique, luxury products from Polish designers. ",
        category:"e-commerce",
        link:"/project/commercial/warsaw-concept-store", 
    },
    
    {
        id:8,
        image:"/kisi.png",
        title:"Kisi-Kisi",
        role:"developer", 
        stack:"#custom-wordpress #lottie",
        description:"A website for Kisi-Kisi - a family run company that sells beetroot kvas. ",
        category:"e-commerce",
        link: "/project/commercial/kisi-kisi",
       
    },
    {
        id:21,
        image:"/digital_festival.png",
        role:"developer", 
        stack:"#custom-wordpress, #php, #javascript, #jquery, #scss, #acf",
        title:"Digital Festival",
        description:"A website for Digital Festival, containing schedules, news, podcasts, event descriptions and more. ",
        category:"wordpress cms",
        link: "/project/commercial/digital_festival",
       
    },
    {
        id:22,
        image:"/digital_ars.png",
        role:"developer", 
        stack:"#custom-wordpress, #php, #javascript, #jquery, #scss, #acf",
        title:"Digital Ars",
        description:"A website for Digital Ars Competition - where contenstasts can upload their projects directly related with AI and Art.",
        category:"wordpress cms",
        link: "/project/commercial/digital_ars",
       
    },
    {
        id:22,
        image:"/edd.png",
        role:"developer", 
        stack:"#custom-wordpress, #php, #javascript, #jquery, #scss, #acf",
        title:"European Digital Days",
        description:"A website for European Digital Days - focused around digitalization and AI.",
        category:"wordpress cms",
        link: "/project/commercial/edd",
       
    },
  
    {
        id:10,
        image:"/orenda.png",
        role:"developer, project manager", 
        title:"Pracownia Orenda",
        stack:"#custom-wordpress",
        description:"Garden designer portfolio website.",
        category:"wordpress cms",
        link: "/project/commercial/orenda-ogrody",
       
    },
    {
        id:11,
        image:"/fashion.png",
        title:"Fashion Biznes",
        role:"developer, project manager", 
        stack:"#custom-wordpress #woocommerce #php #acf #jquery #scss",
        description:"A portal with news about fashion industry and job offers with company and freelancer profiles. ",
        category:"wordpress cms",
        link: "/project/commercial/fashion-biznes",
       
    },
    {
        id:12,
        image:"/michal_luczak.png",
        title:"Michał Łuczak",
        role:"developer",
        stack:"#custom-wordpress",
        description:"Photographer portfolio website ",
        category:"wordpress cms",
        link: "/project/commercial/michal-luczak",
    },
    {
        id:13,
        image:"/zankru.png",
        title:"Zankru",
        role:"developer",
        stack:"#custom-wordpress",
        description:"Fashion designer and artist portfolio website. ",
        category:"wordpress cms",
        link: "/project/commercial/zankru",
       
    },
    {
        id:14,
        image:"/jan_brykczynski.png",
        title:"Jan Brykczynski",
        role:"developer",
        stack:"#custom-wordpress",
        description:"Photographer portfolio website. ",
        category:"wordpress cms",
        link: "/project/commercial/jan-brykczynski",
       
    },
    {
        id:15,
        image:"/oaktopus.png",
        title:"Oaktopus Records",
        role:"developer",
        stack:"#wordpress",
        description:"Record label website. ",
        category:"wordpress cms",
        link: "/project/commercial/oaktopus-records",
       
    },
    {
        id:1,
        image:"/6x7_btr.png",
        title:"6X7 Proffesional Photography",
        role:"developer, e-commerce adminitrator",
        stack:"#custom-wordpress #woocommerce #php #acf #jquery #scss",
        description:"A shop for a company that sells film cameras and distributes Leica in Poland. ",
        category:"e-commerce",
        link: "/project/commercial/6x7",
       
    },
    {
        id:18,
        image:"/polish_inventors.png",
        role:"developer", 
        stack:"#android-studio #java #google-store",
        title:"Real Life Superheroes – Polish Inventors",
        description:"An interactive e-book for children.  I was responsible for programming, interaction and animations. ",
        category:"applications",
       
    },
    {
        id:19,
        image:"/znikniecie_bialej.png",
        role:"developer", 
        stack:"#android-studio #java #google-store",
        title:"The mysterious disappearance of a white lady",
        description:"An interactive e-book for children.  I was responsible for programming, interaction and animations. ",
        category:"applications",
       
    },
    {
        id:20,
        image:"/kafelki.jpg",
        role:"developer", 
        stack:"#android-studio #java #interactive-kiosk",
        title:"Kubicki Stables",
        description:"An interactive e-book for children.  I was responsible for programming, interaction and animations. ",
        category:"applications",
       
    },

]

export default data;